#!/bin/sh
set -e

PYTHON_VERSION=$(python3 -V | tail -c 7 | sed 's/ //' | cut -c-4 | sed -e 's/^[ \t]*//')

# Fix python dependencies, make python 3 symlink

if [ -L "/usr/lib/python3/dist-packages/piper" ]; then
    echo "Piper symlink exists, nothing to do"
    echo "Continuing to start service"
else
    echo "Piper symlink does not exists, creating symlink for python $PYTHON_VERSION"
    ln -s /usr/lib/python$PYTHON_VERSION/site-packages/piper /usr/lib/python3/dist-packages
fi

